Fix gitlab:*:check Rake tasks
Since code isn't eager loaded in Rake tasks, running `gitlab-rake
gitlab:artifacts:check` would result in:

```
NoMethodError: private method `logger' called for Google::Apis:Module
```

To ensure the Google API logger is available, we explicitly require it
in the `fix_google_api_logger` method.

Closes https://gitlab.com/gitlab-org/gitlab/-/issues/225845