Ensure EE use top-level DesignManagement namespace
This change is part of
https://gitlab.com/gitlab-org/gitlab/-/issues/212566 to move all Design
Management code to FOSS.

A job began failing in an MR for moving the Design Management services
I was preparing due to:

    NameError: uninitialized constant EE::DesignManagement::Design

When `EE::Notable` referred to `DesignManagement::Design` here:

https://gitlab.com/gitlab-org/gitlab/-/blob/e75b3b5aba5a36ac59f3b2b4891c6d1e13eb0b44/ee/app/models/concerns/ee/noteable.rb#L27

This changes all references to `DesignManagement` to use
`::DesignManagement` from classes within `/ee`.