Coerce CI auto_retry max value to an integer
Users that used a string (e.g. `'3'` instead of 3) would encounter
an exception such as:

```
ArgumentError: comparison of String with 0 failed
```

Closes https://gitlab.com/gitlab-org/gitlab/-/issues/233035