Update make to generate `testdata/scratch` dir
When running the gitaly tests for the first time to see an error message
to run `make prepare-tests` but then after running the tests again you
start seeing the following error message:

```
Error:  Received unexpected error:
listen unix testdata/scratch/gitaly-8674665223082153551.sock: bind: no
such file or directory
```

This is because the directory `testdata/scratch` is not created.