Fixes nil error in cluster app feature specs
When run locally, we move on to the next step immediately which means
that the application creation request is not even sent to the server.
This causes a nil error in the next step:

```
NoMethodError:
undefined method `make_installing!' for nil:NilClass
./spec/features/clusters/installing_applications_shared_examples.rb:196
```